### ISSUE TITLE
How do I host my own?

### ISSUE THREAD

**Issue by fubz** [nunux-keeper/keeper-web-app#11]
I ran the docker build and started hosting keeper from a docker container.

I navigate to the application by directing my web browser to 192.168.1.4:4000 (4000 is the external container port I am using), which promptly redirects me to:

https://login.nunux.org/auth/realms/nunux.org/protocol/openid-connect/auth?client_id=nunux-keeper-app&redirect_uri=http%3A%2F%2F192.168.1.4%3A4000%2Fdocuments&state=908eb597-3f15-45ca-ba29-0e27d95f8bb2&nonce=6eb372bd-13a1-49b4-8ee3-539d14f0a5c5&response_mode=fragment&response_type=code&scope=openid

I believe I am missing a configuration setting.  Would you happen to know what I am missing? 

Please let me know if any more information is required.

**Comment by ncarlier** [comment]
Hello,
for now there is some steps to follow in order to have have a fully self hosted Keeper. I planned to work on a "ready to deploy" repository and a quick blog post.

Nevertheless, here the steps to install a complete setup:

- Install MongoDB
- Install ElasticSearch
- Install Redis
- Install and configure [Keycloak](https://hub.docker.com/r/jboss/keycloak/)
  - Go to the admin console and create a Realm and a client for the Web App
  - Save the public key of your new Realm `/var/opt/keeper/my-pubkey.pem`
- Install and configure the API: https://github.com/nunux-keeper/keeper-core-api#installation
  - Use the previous public key generated by keycloak `APP_TOKEN_PUB_KEY=/var/opt/keeper/my-pubkey.pem`
- Install and configure the Web App: https://github.com/nunux-keeper/keeper-web-app#configuration
  - Set the variable REACT_APP_API_ROOT to the correct API endpoint
  - Replace (or override with the docker volume option) the `public/keycloak.json` file with your (check the installation panel of your Keycloak client)

Then, it should be ok :clap:

I am completely aware that is not so simple. And I will work on a fully automated recipes based on Docker compose.

**Comment by fubz** [comment]
Thank you, I appreciate the write up.
Not the worst install by any means; but maintaining certainly will not be fun.

I look forward to the complete automated install.  This application is incredible and just what I have been looking for.  Great job.

**Comment by ncarlier** [comment]
Hello,

here the automated installer: https://github.com/nunux-keeper/keeper-docker

Regards.
