### ISSUE TITLE
Getting started part is not correct

### ISSUE THREAD

**Issue by markelog** [nunux-keeper/keeper-web-app#13]
In https://github.com/nunux-keeper/keeper-web-app/tree/556e115f73592355e9bfb90a37a2cf8bd61a9c4c#getting-started it says to do this:

```bash
$ git clone https://github.com/nunux-keeper/keeper-web-app.git
$ cd keeper-web-app
$ npm install       # Install Node modules listed in ./package.json (may take a
                    # while the first time)
$ npm start         # Compile and launch
```

When these commands are executed new tab is opened, which immediately redirects me to here – https://login.nunux.org/auth/realms/nunux.org/protocol/openid-connect/auth?client_id=nunux-keeper-app&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Fdocuments&state=99b7c005-f0df-46ff-b7e3-3165c646ebaa&nonce=b4d093d9-c6b8-4e39-bbfb-8fd6a53cf8ad&response_mode=fragment&response_type=code&scope=openid

-- 

When I try a docker approach, with

```bash
$ git clone https://github.com/nunux-keeper/keeper-web-app.git
$ cd keeper-web-app
$ make build start logs  # Build Docker image and start it
```

I get

```bash
$ make build start logs
make: *** No rule to make target `build'.  Stop.
```

It seems readme is incorrect?

**Comment by ncarlier** [comment]
Hello,

This project (`keeper-web-app`) is only the client webapp of the API backend (https://github.com/nunux-keeper/keeper-core-api). If you want to self host the complete solution, you have also to deploy the API.
I invite you to have a look to this article (written in my poor English ;) ): https://keeper.nunux.org/blog/2017/05/17/3-self-hosted/

I created another project to simplify the deployment of Nunux Keeper: https://github.com/nunux-keeper/keeper-docker

By default the webapp client uses the official hosted API. You can change this by setting this environment variable before the build phase:

```bash
cat ./etc/default/dev.env
REACT_APP_API_ROOT=https://localhost/keeper/v2
```

You right the getting started section is a bit inaccurate.

The correct command is: `make image start`

Btw this make task is used essentially for development purpose. If you want to build the static Webapp I recommend you to run this command: `DEPLOY_DIR=/var/www/html/keeper make install`

This will install the build result into the `/var/www/html/keeper`. Feel free to use your own deployment dir.

I will update the README in order to be more useful.

Thanks

**Comment by markelog** [comment]
Thank you for thoughtful comment :). Maybe it should be documented somewhere here?

Regards,
Oleg
